// ─── FREEZER CATEGORIES (fallback when DB categories are missing) ───
// Colors are one Tailwind step darker than the originals so `text-(--cat)`
// stays readable on the cream (stone-100) page background.
export const CATS = {
  perutnina: { label: 'Perutnina', icon: '🐔', color: '#EA580C', months: 9 },
  goveje: { label: 'Goveje', icon: '🥩', color: '#B91C1C', months: 12 },
  svinjsko: { label: 'Svinjsko', icon: '🥓', color: '#BE123C', months: 6 },
  riba: { label: 'Riba', icon: '🐟', color: '#0284C7', months: 6 },
  zelenjava: { label: 'Zelenjava', icon: '🥦', color: '#16A34A', months: 12 },
  sadje: { label: 'Sadje', icon: '🍓', color: '#9333EA', months: 12 },
  pripravljena: { label: 'Pripravljena jed', icon: '🍲', color: '#D97706', months: 3 },
  pecivo: { label: 'Pecivo', icon: '🍞', color: '#B45309', months: 6 },
  psi: { label: 'Za psa', icon: '🐕', color: '#7C3AED', months: 6 },
  drugo: { label: 'Drugo', icon: '❄️', color: '#78716C', months: 6 },
};

// Freezer add-flow autocomplete suggestions, per locale. The picked name is
// inserted verbatim into the DB, so shared lists can contain mixed-language
// names — the shopping `detectCategory` regexes match both languages.
export const SUGG = {
  sl: [
    { n: 'Piščančja prsa', c: 'perutnina' },
    { n: 'Piščančja bedra', c: 'perutnina' },
    { n: 'Puranja prsa', c: 'perutnina' },
    { n: 'Goveja zrezek', c: 'goveje' },
    { n: 'Mleto goveje', c: 'goveje' },
    { n: 'Goveja juha (kosti)', c: 'goveje' },
    { n: 'Svinjski zrezek', c: 'svinjsko' },
    { n: 'Svinjska rebra', c: 'svinjsko' },
    { n: 'Mleto svinjsko', c: 'svinjsko' },
    { n: 'Losos file', c: 'riba' },
    { n: 'Brancin', c: 'riba' },
    { n: 'Kozice', c: 'riba' },
    { n: 'Brokoli', c: 'zelenjava' },
    { n: 'Špinača', c: 'zelenjava' },
    { n: 'Grah', c: 'zelenjava' },
    { n: 'Mešana zelenjava', c: 'zelenjava' },
    { n: 'Jagode', c: 'sadje' },
    { n: 'Borovnice', c: 'sadje' },
    { n: 'Bolognese', c: 'pripravljena' },
    { n: 'Gulaž', c: 'pripravljena' },
    { n: 'Piščančja juha', c: 'pripravljena' },
    { n: 'Lazanja', c: 'pripravljena' },
    { n: 'Kruh', c: 'pecivo' },
    { n: 'Pica testo', c: 'pecivo' },
    { n: 'Burek', c: 'pecivo' },
    { n: 'Sladoled', c: 'drugo' },
    { n: 'Maslo', c: 'drugo' },
    { n: 'Pasja hrana - govedina', c: 'psi' },
    { n: 'Pasja hrana - piščanec', c: 'psi' },
  ],
  en: [
    { n: 'Chicken breast', c: 'perutnina' },
    { n: 'Chicken thighs', c: 'perutnina' },
    { n: 'Turkey breast', c: 'perutnina' },
    { n: 'Beef steak', c: 'goveje' },
    { n: 'Ground beef', c: 'goveje' },
    { n: 'Beef broth (bones)', c: 'goveje' },
    { n: 'Pork chop', c: 'svinjsko' },
    { n: 'Pork ribs', c: 'svinjsko' },
    { n: 'Ground pork', c: 'svinjsko' },
    { n: 'Salmon fillet', c: 'riba' },
    { n: 'Sea bass', c: 'riba' },
    { n: 'Shrimp', c: 'riba' },
    { n: 'Broccoli', c: 'zelenjava' },
    { n: 'Spinach', c: 'zelenjava' },
    { n: 'Peas', c: 'zelenjava' },
    { n: 'Mixed vegetables', c: 'zelenjava' },
    { n: 'Strawberries', c: 'sadje' },
    { n: 'Blueberries', c: 'sadje' },
    { n: 'Bolognese', c: 'pripravljena' },
    { n: 'Goulash', c: 'pripravljena' },
    { n: 'Chicken soup', c: 'pripravljena' },
    { n: 'Lasagna', c: 'pripravljena' },
    { n: 'Bread', c: 'pecivo' },
    { n: 'Pizza dough', c: 'pecivo' },
    { n: 'Burek', c: 'pecivo' },
    { n: 'Ice cream', c: 'drugo' },
    { n: 'Butter', c: 'drugo' },
    { n: 'Dog food - beef', c: 'psi' },
    { n: 'Dog food - chicken', c: 'psi' },
  ],
};

// Shopping autocomplete items, per locale (inserted verbatim as item names)
export const SHOP_SUGG = {
  sl: [
    'Mleko',
    'Jajca',
    'Kruh',
    'Maslo',
    'Sir',
    'Jogurt',
    'Smetana',
    'Skuta',
    'Banane',
    'Jabolka',
    'Paradižnik',
    'Kumare',
    'Paprika',
    'Čebula',
    'Česen',
    'Krompir',
    'Solata',
    'Korenje',
    'Limone',
    'Pomaranče',
    'Avokado',
    'Piščančja prsa',
    'Mleto goveje',
    'Šunka',
    'Salama',
    'Riž',
    'Testenine',
    'Moka',
    'Sladkor',
    'Sol',
    'Poper',
    'Olje',
    'Kis',
    'Kava',
    'Čaj',
    'Sok',
    'Voda',
    'Pivo',
    'Vino',
    'Toaletni papir',
    'Pralni prašek',
    'Detergent',
    'Gobice',
    'Pasja hrana',
    'Priboljški za psa',
    'Čokolada',
    'Keksi',
    'Čips',
    'Sladoled',
  ],
  en: [
    'Milk',
    'Eggs',
    'Bread',
    'Butter',
    'Cheese',
    'Yogurt',
    'Cream',
    'Cottage cheese',
    'Bananas',
    'Apples',
    'Tomatoes',
    'Cucumbers',
    'Bell peppers',
    'Onions',
    'Garlic',
    'Potatoes',
    'Lettuce',
    'Carrots',
    'Lemons',
    'Oranges',
    'Avocado',
    'Chicken breast',
    'Ground beef',
    'Ham',
    'Salami',
    'Rice',
    'Pasta',
    'Flour',
    'Sugar',
    'Salt',
    'Pepper',
    'Oil',
    'Vinegar',
    'Coffee',
    'Tea',
    'Juice',
    'Water',
    'Beer',
    'Wine',
    'Toilet paper',
    'Laundry detergent',
    'Dish soap',
    'Sponges',
    'Dog food',
    'Dog treats',
    'Chocolate',
    'Cookies',
    'Chips',
    'Ice cream',
  ],
};

// Freezer icon choices
export const FICONS = ['🏠', '🏡', '🏢', '🚗', '🏔️', '🏗️', '🏪', '⛺'];

// Quick quantity options (freezer add flow), per locale — stored as item.qty.
// Two groups rendered as one scrollable chip row: counts first, then measures.
export const QO = {
  sl: { counts: ['1 kos', '2 kosa', '3 kosi'], measures: ['100g', '250g', '500g', '1kg', '500ml', '1L'] },
  en: { counts: ['1 pc', '2 pcs', '3 pcs'], measures: ['100g', '250g', '500g', '1kg', '500ml', '1L'] },
};
