// ─── FREEZER CATEGORIES (fallback when DB categories are missing) ───
export const CATS = {
  perutnina: { label: 'Perutnina', icon: '🐔', color: '#F97316', months: 9 },
  goveje: { label: 'Goveje', icon: '🥩', color: '#DC2626', months: 12 },
  svinjsko: { label: 'Svinjsko', icon: '🥓', color: '#E11D48', months: 6 },
  riba: { label: 'Riba', icon: '🐟', color: '#0EA5E9', months: 6 },
  zelenjava: { label: 'Zelenjava', icon: '🥦', color: '#22C55E', months: 12 },
  sadje: { label: 'Sadje', icon: '🍓', color: '#A855F7', months: 12 },
  pripravljena: { label: 'Pripravljena jed', icon: '🍲', color: '#F59E0B', months: 3 },
  pecivo: { label: 'Pecivo', icon: '🍞', color: '#D97706', months: 6 },
  psi: { label: 'Za psa', icon: '🐕', color: '#8B5CF6', months: 6 },
  drugo: { label: 'Drugo', icon: '❄️', color: '#64748B', months: 6 },
};

// Freezer add-flow autocomplete suggestions
export const SUGG = [
  { n: 'Piščančja prsa', c: 'perutnina' },
  { n: 'Piščančja bedra', c: 'perutnina' },
  { n: 'Puranja prsa', c: 'perutnina' },
  { n: 'Goveja zrezek', c: 'goveje' },
  { n: 'Mleto goveje', c: 'goveje' },
  { n: 'Goveja juha (kosti)', c: 'goveje' },
  { n: 'Svinjski zrezek', c: 'svinjsko' },
  { n: 'Svinjska rebra', c: 'svinjsko' },
  { n: 'Mleto svinjsko', c: 'svinjsko' },
  { n: 'Losos file', c: 'riba' },
  { n: 'Brancin', c: 'riba' },
  { n: 'Kozice', c: 'riba' },
  { n: 'Brokoli', c: 'zelenjava' },
  { n: 'Špinača', c: 'zelenjava' },
  { n: 'Grah', c: 'zelenjava' },
  { n: 'Mešana zelenjava', c: 'zelenjava' },
  { n: 'Jagode', c: 'sadje' },
  { n: 'Borovnice', c: 'sadje' },
  { n: 'Bolognese', c: 'pripravljena' },
  { n: 'Gulaž', c: 'pripravljena' },
  { n: 'Piščančja juha', c: 'pripravljena' },
  { n: 'Lazanja', c: 'pripravljena' },
  { n: 'Kruh', c: 'pecivo' },
  { n: 'Pica testo', c: 'pecivo' },
  { n: 'Burek', c: 'pecivo' },
  { n: 'Sladoled', c: 'drugo' },
  { n: 'Maslo', c: 'drugo' },
  { n: 'Pasja hrana - govedina', c: 'psi' },
  { n: 'Pasja hrana - piščanec', c: 'psi' },
];

// Shopping autocomplete items
export const SHOP_SUGG = [
  'Mleko',
  'Jajca',
  'Kruh',
  'Maslo',
  'Sir',
  'Jogurt',
  'Smetana',
  'Skuta',
  'Banane',
  'Jabolka',
  'Paradižnik',
  'Kumare',
  'Paprika',
  'Čebula',
  'Česen',
  'Krompir',
  'Solata',
  'Korenje',
  'Limone',
  'Pomaranče',
  'Avokado',
  'Piščančja prsa',
  'Mleto goveje',
  'Šunka',
  'Salama',
  'Riž',
  'Testenine',
  'Moka',
  'Sladkor',
  'Sol',
  'Poper',
  'Olje',
  'Kis',
  'Kava',
  'Čaj',
  'Sok',
  'Voda',
  'Pivo',
  'Vino',
  'Toaletni papir',
  'Pralni prašek',
  'Detergent',
  'Gobice',
  'Pasja hrana',
  'Priboljški za psa',
  'Čokolada',
  'Keksi',
  'Čips',
  'Sladoled',
];

// Freezer icon choices
export const FICONS = ['🏠', '🏡', '🏢', '🚗', '🏔️', '🏗️', '🏪', '⛺'];

// Quick quantity options (freezer add flow)
export const QO = ['100g', '250g', '500g', '1kg', '1 kos', '2 kosa', '500ml', '1L'];
